// <auto-generated />
using System;
using ContainerControl.Modules.Delivery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContainerControl.Modules.Delivery.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20260925181320_TrafficSlots")]
    partial class TrafficSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContainerControl.Modules.Delivery.Runs.DeploymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommandJson")
                        .HasColumnType("text");

                    b.Property<string>("ComposeYaml")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Exposed")
                        .HasColumnType("boolean");

                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int?>("InternalPort")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "CreatedAtUtc");

                    b.ToTable("deployments", "delivery");
                });

            modelBuilder.Entity("ContainerControl.Modules.Delivery.Runs.TrafficSlot", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CandidatePercent")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateSlot")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LiveSlot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreviousSlot")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ApplicationId");

                    b.ToTable("traffic_slots", "delivery");
                });

            modelBuilder.Entity("ContainerControl.Modules.Delivery.Runs.WorkerLease", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ApplicationId", "Environment");

                    b.ToTable("worker_lease", "delivery");
                });

            modelBuilder.Entity("ContainerControl.SharedKernel.Persistence.ModuleBoundary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("module_boundary", "delivery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleName = "Delivery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
