// <auto-generated />
using System;
using ContainerControl.Modules.Access.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContainerControl.Modules.Access.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20260923163355_InitialAccess")]
    partial class InitialAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("audit_entries", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.BreakGlass.BreakGlassGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("break_glass_grants", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Permissions.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "access");

                    b.HasData(
                        new
                        {
                            Code = "access.users.read",
                            Description = "View provisioned user accounts.",
                            DisplayName = "Read users",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.users.manage",
                            Description = "Create and disable user accounts.",
                            DisplayName = "Manage users",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.teams.manage",
                            Description = "Create teams and memberships.",
                            DisplayName = "Manage teams",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.roles.manage",
                            Description = "Compose roles from the permission catalog.",
                            DisplayName = "Manage roles",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.tokens.manage",
                            Description = "Issue and revoke CI API tokens.",
                            DisplayName = "Manage API tokens",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.breakglass.grant",
                            Description = "Grant a short-lived permission.",
                            DisplayName = "Grant break-glass",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "access.audit.read",
                            Description = "Read the append-only audit log.",
                            DisplayName = "Read audit",
                            Module = "Access"
                        },
                        new
                        {
                            Code = "platform.hosts.manage",
                            Description = "Register and update Docker hosts.",
                            DisplayName = "Manage Docker hosts",
                            Module = "Platform"
                        },
                        new
                        {
                            Code = "platform.quotas.manage",
                            Description = "Set team CPU, memory, and storage quotas.",
                            DisplayName = "Manage quotas",
                            Module = "Platform"
                        },
                        new
                        {
                            Code = "platform.settings.manage",
                            Description = "Change control-plane settings.",
                            DisplayName = "Manage platform settings",
                            Module = "Platform"
                        },
                        new
                        {
                            Code = "platform.capacity.read",
                            Description = "Read host capacity.",
                            DisplayName = "Read capacity",
                            Module = "Platform"
                        },
                        new
                        {
                            Code = "registries.read",
                            Description = "View registry connections.",
                            DisplayName = "Read registries",
                            Module = "Registries"
                        },
                        new
                        {
                            Code = "registries.manage",
                            Description = "Create and update registry connections.",
                            DisplayName = "Manage registries",
                            Module = "Registries"
                        },
                        new
                        {
                            Code = "apps.read",
                            Description = "View applications the caller may access.",
                            DisplayName = "Read applications",
                            Module = "Applications"
                        },
                        new
                        {
                            Code = "apps.write",
                            Description = "Create and update applications.",
                            DisplayName = "Write applications",
                            Module = "Applications"
                        },
                        new
                        {
                            Code = "secrets.read",
                            Description = "View secret names and injection mode.",
                            DisplayName = "Read secrets",
                            Module = "Secrets"
                        },
                        new
                        {
                            Code = "secrets.manage",
                            Description = "Write secret values for non-production environments.",
                            DisplayName = "Manage secrets",
                            Module = "Secrets"
                        },
                        new
                        {
                            Code = "secrets.manage.prod",
                            Description = "Write secret values for production.",
                            DisplayName = "Manage production secrets",
                            Module = "Secrets"
                        },
                        new
                        {
                            Code = "deploy.execute",
                            Description = "Deploy and redeploy an application.",
                            DisplayName = "Execute deploys",
                            Module = "Delivery"
                        },
                        new
                        {
                            Code = "deploy.approve",
                            Description = "Accept a deploy that is waiting for approval.",
                            DisplayName = "Approve deploys",
                            Module = "Delivery"
                        },
                        new
                        {
                            Code = "deploy.rollback",
                            Description = "Restore the last successful desired state.",
                            DisplayName = "Roll back deploys",
                            Module = "Delivery"
                        },
                        new
                        {
                            Code = "edge.certs.manage",
                            Description = "Upload and replace certificates.",
                            DisplayName = "Manage certificates",
                            Module = "Edge"
                        },
                        new
                        {
                            Code = "edge.dns.manage",
                            Description = "Save domains that applications may claim.",
                            DisplayName = "Manage allowed domains",
                            Module = "Edge"
                        },
                        new
                        {
                            Code = "runtime.logs.read",
                            Description = "Read container logs.",
                            DisplayName = "Read logs",
                            Module = "Runtime"
                        },
                        new
                        {
                            Code = "runtime.stats.read",
                            Description = "Read CPU and memory stats.",
                            DisplayName = "Read stats",
                            Module = "Runtime"
                        },
                        new
                        {
                            Code = "runtime.control",
                            Description = "Start, stop, and restart services.",
                            DisplayName = "Control runtime",
                            Module = "Runtime"
                        });
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.PermissionRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permission_roles", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.PermissionRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("permission_role_permissions", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.UserPermissionRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_permission_roles", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("teams", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Teams.TeamMembership", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("team_memberships", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Tokens.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("api_tokens", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "access");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.PermissionRolePermission", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContainerControl.Modules.Access.Domain.Roles.PermissionRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.UserPermissionRole", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Roles.PermissionRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Teams.TeamMembership", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Teams.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Tokens.ApiToken", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContainerControl.Modules.Access.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Roles.PermissionRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ContainerControl.Modules.Access.Domain.Teams.Team", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
